name: github actions Demo

on:
  issues:
    types: [labeled]

jobs:
  build:
    if: |
        github.event.label.name == 'worldgifs' &&  
        github.actor == 'rpappalax' 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C4YD9HR2S\",\"text\":\"world gifs label created\"}'
