name: github actions Demo

on:
  issues:
    types: [labeled]

jobs:
  build:
    if: |
        github.event.label.name == 'eng:ui-test' ||
        github.event.label.name == 'eng:intermittent-test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        ISSUE_LINK: 'http://github.com/rpappalax' 
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"${{env.SLACK_CHANNEL_ID }}\",\"text\":\"${{env.ISSUE_LINK }}\"}'
