name: github actions Demo

on:
  issues:
    types: [labeled]

jobs:
  build:
    if: |
        github.event.label.name == 'eng:ui-test' ||
        github.event.label.name == 'eng:intermittent-test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        ISSUE_LINK: 'https://github.com/rpappalax/demo-slackenbotten/issues/${{github.event.issue.number}}'
      with:
        args: '{\"channel\":\"${{env.SLACK_CHANNEL_ID }}\",\"text\":\"${{env.ISSUE_LINK }}\"}'
