name: github actions Demo

on:
  issues:
    types: [labeled]

jobs:
  build:
    if: |
        github.event.label.name == 'eng:ui-test' ||
        github.event.label.name == 'eng:intermittent-test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: 'UI or intermittent test issue' 
        SLACK_MESSAGE: 'https://github.com/rpappalax/demo-slackenbotten/issues/${{github.event.issue.number}}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
