name: github actions Demo

on:
  issues:
    types: [labeled]

jobs:
  intermittent-test:
    if: |
        github.event.label.name == 'eng:intermittent-test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: 'Intermittent Test: ${{github.event.issue.title}}' 
        MSG_MINIMAL: true 
        SLACK_MESSAGE: '<https://github.com/rpappalax/demo-slackenbotten/issues/${{github.event.issue.number}}|${{github.event.issue.title}}>'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ''
  disabled-test:
    if: |
        github.event.label.name == 'eng:disabled-test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: '${{github.event.issue.title}}' 
        MSG_MINIMAL: true 
        SLACK_MESSAGE: 'https://github.com/rpappalax/demo-slackenbotten/issues/${{github.event.issue.number}}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ''
